[project]
name = "lems-anechoic"
version = "0.1.0"
description = "LEMS anechoic chamber test scripts"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ # Serial communication, used by pyvisa-py
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "pyvisa>=1.14.1", # PyVISA backend for serial connections
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
    "F541", # f-string without any placeholders
]
